using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FaturaIslem : Form
    {
        public FaturaIslem()
        {
            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard
            tblcarıTableAdapter1.Fill(dbTeknikServisDataSet91.TBLCARI);
            // This line of code is generated by Data Source Configuration Wizard
            tblpersonelTableAdapter1.Fill(dbTeknikServisDataSet101.TBLPERSONEL);
            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard
            tblurunhareketTableAdapter3.Fill(dbTeknikServisDataSet251.TBLURUNHAREKET);
        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
        private void FaturaIslem_Load(object sender, EventArgs e)
        {
            var degerler = from u in db.TBLFATURABILGI
                           select new
                           {
                               u.Id,
                               u.SıraNo,
                               u.Seri,
                               u.Personel,
                               u.Tarih,
                               u.VergiDairesi,
                               u.Cari
                           };
            gridControl1.DataSource = degerler.ToList();
        }

        private void BtnKaydet_Click(object sender, EventArgs e)
        {
            TBLFATURABILGI t = new TBLFATURABILGI();
            t.Seri = (lookUpEdit3.EditValue.ToString());
            t.SıraNo = Convert.ToInt32(txtmarka.Text);
            t.Tarih= DateTime.Now;
            t.VergiDairesi = txtstok.Text;
            t.Cari = lookUpEdit1.EditValue.ToString();
            t.Personel = lookUpEdit4.EditValue.ToString();
            db.TBLFATURABILGI.Add(t);
            db.SaveChanges();
            MessageBox.Show("Fatura  başarıyla kaydedildi", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void txtalis_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void lookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {


        }

        private void btnlistele_Click(object sender, EventArgs e)
        {
            var degerler = from u in db.TBLFATURABILGI
                           select new
                           {
                               u.Id,
                               u.SıraNo,
                               u.Seri,
                               u.Personel,
                               u.Tarih,
                               u.VergiDairesi,
                               u.Cari
                           };
            gridControl1.DataSource = degerler.ToList();
        }

        private void btnsil_Click(object sender, EventArgs e)
        {
            int id = int.Parse(textEdit1.Text);
            var deger = db.TBLFATURABILGI.Find(id);
            db.TBLFATURABILGI.Remove(deger);
            db.SaveChanges();
            MessageBox.Show("Ürün Silinmiştir", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Stop);
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {

            textEdit1.Text = gridView1.GetFocusedRowCellValue("Id").ToString();
            lookUpEdit3.Text = gridView1.GetFocusedRowCellValue("Seri").ToString();
            txtmarka.Text = gridView1.GetFocusedRowCellValue("SıraNo").ToString();
            txtstok.Text = gridView1.GetFocusedRowCellValue("VergiDairesi").ToString();
            lookUpEdit1.Text = gridView1.GetFocusedRowCellValue("Cari").ToString();
            lookUpEdit4.Text = gridView1.GetFocusedRowCellValue("Personel").ToString();

           

           
        }

        private void btnguncelle_Click(object sender, EventArgs e)
        {
            int id = int.Parse(textEdit1.Text);
            var deger = db.TBLFATURABILGI.Find(id);
            deger.Seri = (lookUpEdit3.EditValue.ToString());
            deger.SıraNo= Convert.ToInt32(txtmarka.Text);
            deger.Tarih = DateTime.Now;
            deger.Cari= lookUpEdit1.EditValue.ToString();
            deger.VergiDairesi = txtstok.Text;
            deger.Personel= lookUpEdit4.EditValue.ToString();
            db.SaveChanges();
            MessageBox.Show("Faturanız Güncellenmiştir", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Warning);
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            receiptTextbox.Clear();
            receiptTextbox.AppendText(Environment.NewLine);
            receiptTextbox.AppendText("\t\t\t\tFATURALANDIRMA" + Environment.NewLine);
            receiptTextbox.AppendText("\t\t\t\t*****************" + Environment.NewLine);
            receiptTextbox.AppendText("\t\t\t\t" + DateTime.Now + "\t"  + Environment.NewLine);
            receiptTextbox.AppendText(Environment.NewLine);
            receiptTextbox.AppendText(Environment.NewLine);
            string a = gridView1.GetFocusedRowCellValue("Id").ToString();
            string b = gridView1.GetFocusedRowCellValue("Seri").ToString();
            string c = gridView1.GetFocusedRowCellValue("SıraNo").ToString();
            string d = gridView1.GetFocusedRowCellValue("VergiDairesi").ToString();
            string x = gridView1.GetFocusedRowCellValue("Cari").ToString();
            string f = gridView1.GetFocusedRowCellValue("Personel").ToString();
            receiptTextbox.AppendText("\t"+"Fatura ID:" + a + Environment.NewLine);
            receiptTextbox.AppendText("\t"+"Seri No:" + b + Environment.NewLine);
            receiptTextbox.AppendText("\t"+"Sıra No:" + c + Environment.NewLine);
            receiptTextbox.AppendText("\t" + "Vergi Dairesi:" + d + Environment.NewLine);
            receiptTextbox.AppendText("\t" + "Cari:" + x + Environment.NewLine);
            receiptTextbox.AppendText("\t" + "Personel:" + f + Environment.NewLine);
            
        
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            string path = "hazal.pdf";
            gridControl1.ExportToPdf(path);
        }
    }
}
