using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmArızaDetay : Form
    {
        public FrmArızaDetay()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard
            tblurunkabulTableAdapter1.Fill(dbTeknikServisDataSet171.TBLURUNKABUL);
            // This line of code is generated by Data Source Configuration Wizard
            tblurunhareketTableAdapter2.Fill(dbTeknikServisDataSet181.TBLURUNHAREKET);
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
            TBLURUNTAKIP t = new TBLURUNTAKIP();
            t.AÇIKLAMA = richTextBox1.Text;
            t.SERİNO = (lookUpEdit1.EditValue.ToString());
            t.TARIH = DateTime.Parse(txtkategori.Text);
            db.TBLURUNTAKIP.Add(t);
            db.SaveChanges();

            TBLURUNKABUL a = new TBLURUNKABUL();
            int urunid = Convert.ToInt32(lookUpEdit1.EditValue.ToString());
            a.URUNDURUMDETAY = lookUpEdit1.EditValue.ToString();
            db.TBLURUNKABUL.Add(a);
            db.SaveChanges();
            MessageBox.Show("ARIZA DETAYI GÜNCELLENMİŞTİR.");
        }
        public string urunid,serino;
        private void FrmArızaDetay_Load(object sender, EventArgs e)
        {
             //serino= lookUpEdit1.EditValue.ToString();
        }

        private void txtkategori_Click(object sender, EventArgs e)
        {
            txtkategori.Text= DateTime.Now.ToShortDateString();
        }

        private void richTextBox1_Click(object sender, EventArgs e)
        {
            richTextBox1.Text = urunid;
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
