using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class YeniCari : Form
    {
        public YeniCari()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            illerTableAdapter1.Fill(dbTeknikServisDataSet231.iller);
            // This line of code is generated by Data Source Configuration Wizard
            ilcelerTableAdapter1.Fill(dbTeknikServisDataSet241.ilceler);
        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
        private void YeniCari_Load(object sender, EventArgs e)
        {
            
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            TBLCARI t = new TBLCARI();
            t.AD = txtad.Text;
            t.SOYAD = txtsoyad.Text;
            t.TELEFON = txttelefon.Text;
            t.MAIL = txtmail.Text;
            t.IL = lookUpEdit1.EditValue.ToString();
            t.ILCE = lookUpEdit2.EditValue.ToString();
            t.BANKA = txtbanka.Text;
            t.ADRES = txtadres.Text;
            db.TBLCARI.Add(t);

            db.SaveChanges();
            MessageBox.Show("Yeni Cari Başarıyla Eklenmiştir.", "Bilgi", MessageBoxButtons.OK);
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
