using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmFaturaKalemleri : Form
    {
        public FrmFaturaKalemleri()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tblfaturadetayTableAdapter1.Fill(dbTeknikServisDataSet131.TBLFATURADETAY);
        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
        private void BtnKaydet_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(lookUpEdit1.EditValue);
            var degerler = (from u in db.TBLFATURADETAY
                            select new
                            {
                                u.FATURADETAYID,
                                u.URUN,
                                u.ADET,
                                u.FIYAT,
                                u.FATURAID
                            }).Where(x => x.FATURAID == id);
            gridControl1.DataSource = degerler.ToList();
        }

        private void FrmFaturaKalemleri_Load(object sender, EventArgs e)
        {

        }
    }
}
