using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmPersonel : Form
    {
        public FrmPersonel()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tbldepartmanTableAdapter1.Fill(dbTeknikServisDataSet301.TBLDEPARTMAN);
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
        private void FrmPersonel_Load(object sender, EventArgs e)
        {
            var degerler = from u in db.TBLPERSONEL
                           select new
                           {
                               u.ID,
                               u.AD,
                               u.SOYAD,
                               u.DEPARTMAN,
                               u.MAIL,
                               u.TELEFON,
                           };
            gridControl1.DataSource = degerler.ToList();
          
            string ad1, soyad1;
            ad1 = db.TBLPERSONEL.First(x => x.ID == 2).AD;
            soyad1 = db.TBLPERSONEL.First(x => x.ID == 2).SOYAD;
            labelControl7.Text = db.TBLPERSONEL.First(x => x.ID == 2).TBLDEPARTMAN.AD;
            labelControl6.Text = db.TBLPERSONEL.First(x => x.ID == 2).MAIL;
            labelControl8.Text = ad1 + " " + soyad1;

            string ad2, soyad2;
            ad2 = db.TBLPERSONEL.First(x => x.ID == 4).AD;
            soyad2 = db.TBLPERSONEL.First(x => x.ID == 4).SOYAD;
            labelControl19.Text = db.TBLPERSONEL.First(x => x.ID == 4).TBLDEPARTMAN.AD;
            labelControl18.Text = db.TBLPERSONEL.First(x => x.ID == 4).MAIL;
            labelControl20.Text = ad2 + " " + soyad2;

            string ad3, soyad3;
            ad3 = db.TBLPERSONEL.First(x => x.ID == 3).AD;
            soyad3 = db.TBLPERSONEL.First(x => x.ID == 3).SOYAD;
            labelControl22.Text = db.TBLPERSONEL.First(x => x.ID == 3).TBLDEPARTMAN.AD;
            labelControl21.Text = db.TBLPERSONEL.First(x => x.ID == 3).MAIL;
            labelControl23.Text = ad3 + " " + soyad3;


            string ad4, soyad4;
            ad4 = db.TBLPERSONEL.First(x => x.ID == 5).AD;
            soyad4 = db.TBLPERSONEL.First(x => x.ID == 5).SOYAD;
            labelControl25.Text = db.TBLPERSONEL.First(x => x.ID == 5).TBLDEPARTMAN.AD;
            labelControl24.Text = db.TBLPERSONEL.First(x => x.ID == 5).MAIL;
            labelControl26.Text = ad4 + " " + soyad4;

        }

        private void BtnKaydet_Click(object sender, EventArgs e)
        {
            TBLPERSONEL t = new TBLPERSONEL();
            t.AD = txtad.Text;
            t.SOYAD = txtsoyad.Text;
            t.MAIL = txtmail.Text;
            t.TELEFON = txttelefon.Text;
            t.DEPARTMAN = byte.Parse(lookUpEdit1.EditValue.ToString());
            t.MAIL = textEdit3.Text;
            t.TELEFON = textEdit4.Text;
            db.TBLPERSONEL.Add(t);
            db.SaveChanges();
            MessageBox.Show("Yeni Personel  Başarıyla Kaydedildi");
        }

        private void btnlistele_Click(object sender, EventArgs e)
        {
            var degerler = from u in db.TBLPERSONEL
                           select new
                           {
                               u.ID,
                               u.AD,
                               u.SOYAD,
                               u.MAIL,
                               u.TELEFON,
                               u.DEPARTMAN,
                           };
            gridControl1.DataSource = degerler.ToList();
        }

        private void btnsil_Click(object sender, EventArgs e)
        {
            int id = int.Parse(txtId.Text);
            var deger = db.TBLPERSONEL.Find(id);
            db.TBLPERSONEL.Remove(deger);
            db.SaveChanges();
            MessageBox.Show("Bu Personel Bilgisi Silinmiştir.", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Stop);
        }

        private void btnguncelle_Click(object sender, EventArgs e)
        {
            int id = int.Parse(txtId.Text);
            var deger = db.TBLPERSONEL.Find(id);
            deger.AD = txtad.Text;
            deger.SOYAD = txtsoyad.Text;
            deger.MAIL = textEdit3.Text;
          
            deger.TELEFON = textEdit4.Text;
            deger.DEPARTMAN = byte.Parse(lookUpEdit1.EditValue.ToString());
            db.SaveChanges();
            MessageBox.Show("Personel Bilgisi Güncellenmiştir", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Warning);
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            txtId.Text = gridView1.GetFocusedRowCellValue("ID").ToString();
            txtad.Text = gridView1.GetFocusedRowCellValue("AD").ToString();
            txtsoyad.Text = gridView1.GetFocusedRowCellValue("SOYAD").ToString();
            lookUpEdit1.Text= gridView1.GetFocusedRowCellValue("DEPARTMAN").ToString();
            textEdit3.Text = gridView1.GetFocusedRowCellValue("MAIL").ToString();
            textEdit4.Text = gridView1.GetFocusedRowCellValue("TELEFON").ToString();
        }
    }
}
