using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MessagingToolkit.QRCode.Codec;

namespace projeDevexpress.Formlar
{
    public partial class FrmQR : Form
    {
        public FrmQR()
        {
            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard
            tblurunhareketTableAdapter3.Fill(dbTeknikServisDataSet201.TBLURUNHAREKET);
        }

        private void BtnKaydet_Click(object sender, EventArgs e)
        {
            QRCodeEncoder kod = new QRCodeEncoder();
            pictureEdit1.Image = kod.Encode((string)lookUpEdit1.EditValue);
        }

        private void FrmQR_Load(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
