using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmUrunAra : Form
    {
        public FrmUrunAra()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tblurunTableAdapter1.Fill(dbTeknikServisDataSet291.TBLURUN);
            // This line of code is generated by Data Source Configuration Wizard
            tblurunTableAdapter2.Fill(dbTeknikServisDataSet292.TBLURUN);
        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
        private void labelControl1_Click(object sender, EventArgs e)
        {

        }

        private void BtnKaydet_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(lookUpEdit1.EditValue);
            var degerler = (from u in db.TBLURUN
                            select new
                            {
                                u.ID,
                                u.AD,
                                u.KATEGORI,
                                u.MARKA,
                                u.SATISFIYAT,
                                u.ALISFIYAT,
                                u.STOK
                            }).Where(x => x.ID == id);
            gridControl1.DataSource = degerler.ToList();
        }
    
    }
}
