using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmYeniÜrün : Form
    {
        public FrmYeniÜrün()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tblkategoriTableAdapter1.Fill(dbTeknikServisDataSet141.TBLKATEGORİ);
        }

        private void txtalis_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
            TBLURUN t = new TBLURUN();
            t.AD = txturun.Text;
            t.MARKA = txtmarka.Text;
            t.ALISFIYAT = decimal.Parse(txtalis.Text);
            t.SATISFIYAT = decimal.Parse(txtsatis.Text);
            t.STOK = short.Parse(txtstok.Text);
            t.DURUM = false;
            t.KATEGORI = Byte.Parse(lookUpEdit1.EditValue.ToString());
            db.TBLURUN.Add(t);
            db.SaveChanges();
            MessageBox.Show("Ürün başarıyla kaydedildi", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void FrmYeniÜrün_Load(object sender, EventArgs e)
        {
           // txturun.Text = "";
            //txtmarka.Text = "";
            //txtalis.Text = "";
            //txtsatis.Text = "";
            //txtstok.Text = "";
           
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
