using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmYeniFatura : Form
    {
        public FrmYeniFatura()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            tblurunhareketTableAdapter3.Fill(dbTeknikServisDataSet261.TBLURUNHAREKET);
            // This line of code is generated by Data Source Configuration Wizard
            tblcarıTableAdapter1.Fill(dbTeknikServisDataSet91.TBLCARI);
            // This line of code is generated by Data Source Configuration Wizard
            tblpersonelTableAdapter1.Fill(dbTeknikServisDataSet271.TBLPERSONEL);
        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
        private void FrmYeniFatura_Load(object sender, EventArgs e)
        {

        }

        private void BtnKaydet_Click(object sender, EventArgs e)
        {
            TBLFATURABILGI t = new TBLFATURABILGI();
            t.Seri = (lookUpEdit1.EditValue.ToString());
            t.SıraNo = Convert.ToInt32(txtmarka.Text);
            t.Tarih = DateTime.Now;
            t.VergiDairesi = txtstok.Text;
            t.Cari = lookUpEdit1.EditValue.ToString();
            t.Personel = lookUpEdit3.EditValue.ToString();
            db.TBLFATURABILGI.Add(t);
            db.SaveChanges();
            MessageBox.Show("Fatura  başarıyla kaydedildi", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }
    }
}
