using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmYeniSatış : Form
    {
        public FrmYeniSatış()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tblurunTableAdapter2.Fill(dbTeknikServisDataSet11.TBLURUN);
            // This line of code is generated by Data Source Configuration Wizard
            tblpersonelTableAdapter1.Fill(dbTeknikServisDataSet271.TBLPERSONEL);
            // This line of code is generated by Data Source Configuration Wizard
            tblcarıTableAdapter1.Fill(dbTeknikServisDataSet281.TBLCARI);
        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
        private void FrmYeniSatış_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dBTeknikServisDataSet1.TBLURUN' table. You can move, or remove it, as needed.
            this.tBLURUNTableAdapter1.Fill(this.dBTeknikServisDataSet1.TBLURUN);
            // TODO: This line of code loads data into the 'dBTeknikServisDataSet.TBLURUN' table. You can move, or remove it, as needed.
            this.tBLURUNTableAdapter.Fill(this.dBTeknikServisDataSet.TBLURUN);

            //lookUpEdit1.Properties.DataSource = (from x in db.TBLURUN
            //                                     select new TBLURUN
            //                                     {
            //                                         AD=x.AD,
            //                                         ID=x.ID
            //                                     }).ToList();

            //lookUpEdit1.Properties.DataSource = db.TBLURUN.ToList();
            
        }
        

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            TBLURUNHAREKET t = new TBLURUNHAREKET();
            t.MUSTERI = lookUpEdit2.EditValue.ToString();
            t.PERSONEL = lookUpEdit3.EditValue.ToString();
            t.TARIH = DateTime.Parse(txtalis.Text);
            t.ADET = short.Parse(txtstok.Text);
            t.URUN = byte.Parse(lookUpEdit1.EditValue.ToString());
            t.FIYAT = decimal.Parse(txtsatis.Text);
            t.URUNSERINO = textEdit2.Text;
            db.TBLURUNHAREKET.Add(t);
            
            db.SaveChanges();
            MessageBox.Show("Ürün başarıyla kaydedildi", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void pictureEdit4_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void txtalis_Click(object sender, EventArgs e)
        {
            txtalis.Text = DateTime.Now.ToShortDateString();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
