using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmYeniArıza : Form
    {
        public FrmYeniArıza()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
            // This line of code is generated by Data Source Configuration Wizard
            tblpersonelTableAdapter1.Fill(dbTeknikServisDataSet161.TBLPERSONEL);
            // This line of code is generated by Data Source Configuration Wizard


            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard
            tblurunhareketTableAdapter5.Fill(dbTeknikServisDataSet211.TBLURUNHAREKET);
            // This line of code is generated by Data Source Configuration Wizard
            tblurunkabulTableAdapter2.Fill(dbTeknikServisDataSet221.TBLURUNKABUL);
            // This line of code is generated by Data Source Configuration Wizard
            tblcarıTableAdapter2.Fill(dbTeknikServisDataSet91.TBLCARI);
        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();
        private void FrmYeniArıza_Load(object sender, EventArgs e)
        {
           
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            TBLURUNKABUL t = new TBLURUNKABUL();
            t.CARI = Convert.ToInt32(CARİ.EditValue.ToString());
            t.PERSONEL = short.Parse(lookUpEdit2.EditValue.ToString());
            t.GELISTARIHI = Convert.ToDateTime(txtalis.Text);
            t.URUNSERINO = lookUpEdit3.EditValue.ToString();
            t.URUNDURUMDETAY = lookUpEdit1.EditValue.ToString();
            db.TBLURUNKABUL.Add(t);

            db.SaveChanges();
            MessageBox.Show("Ürün başarıyla kaydedildi", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void txtalis_Click(object sender, EventArgs e)
        {
            txtalis.Text = DateTime.Now.ToShortDateString();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
