using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace projeDevexpress.Formlar
{
    public partial class FrmÜrünListesi : Form
    {
        public FrmÜrünListesi()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tblkategoriTableAdapter1.Fill(dbTeknikServisDataSet21.TBLKATEGORİ);
        }
        DBTeknikServisEntities1 db = new DBTeknikServisEntities1();

        void metot1()
        {
            var degerler = from u in db.TBLURUN
                           select new
                           {
                               u.ID,
                               u.AD,
                               u.MARKA,
                               u.STOK,
                               KATEGORI = u.TBLKATEGORİ.AD,
                               u.ALISFIYAT,
                               u.SATISFIYAT
                               
        };
            gridControl1.DataSource = degerler.ToList();
        }
        private void FrmÜrünListesi_Load(object sender, EventArgs e)
        {

            Control.CheckForIllegalCrossThreadCalls = false;
            //var degerler= db.TBLURUN.ToList();
            metot1();
                /*lookUpEdit1.Properties.DataSource = (from x in db.TBLURUN
                                                     select new
                                                     {
                                                         KATEGORI = x.TBLKATEGORİ.AD,
                                                     }).ToList();
                */
            //lookUpEdit1.Properties.DataSource = db.TBLKATEGORİ.ToList();


        }

        private void BtnKaydet_Click(object sender, EventArgs e)
        {
            TBLURUN t = new TBLURUN();
            t.AD = txturun.Text;
            t.MARKA = txtmarka.Text;
            t.ALISFIYAT = decimal.Parse(txtalis.Text);
            t.SATISFIYAT = decimal.Parse(txtsatis.Text);
            t.STOK = short.Parse(txtstok.Text);
            t.DURUM = false;
            t.KATEGORI = byte.Parse(lookUpEdit1.EditValue.ToString());
            db.TBLURUN.Add(t);
            db.SaveChanges();
            MessageBox.Show("Ürün başarıyla kaydedildi", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void btnsil_Click(object sender, EventArgs e)
        {
            int id = int.Parse(txtId.Text);
            var deger = db.TBLURUN.Find(id);
            db.TBLURUN.Remove(deger);
            db.SaveChanges();
            MessageBox.Show("Ürün Silinmiştir", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Stop);
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            txtId.Text = gridView1.GetFocusedRowCellValue("ID").ToString();
            txturun.Text = gridView1.GetFocusedRowCellValue("AD").ToString();
            txtmarka.Text = gridView1.GetFocusedRowCellValue("MARKA").ToString();
            txtalis.Text = gridView1.GetFocusedRowCellValue("ALISFIYAT").ToString();
            txtsatis.Text = gridView1.GetFocusedRowCellValue("SATISFIYAT").ToString();
            txtstok.Text = gridView1.GetFocusedRowCellValue("STOK").ToString();

        }

        private void btnguncelle_Click(object sender, EventArgs e)
        {
            int id = int.Parse(txtId.Text);
            var deger = db.TBLURUN.Find(id);
            deger.AD = txturun.Text;
            deger.STOK = short.Parse(txtstok.Text);
            deger.MARKA = txtmarka.Text;
            deger.ALISFIYAT = decimal.Parse(txtalis.Text);
            deger.SATISFIYAT = decimal.Parse(txtsatis.Text);
            deger.KATEGORI = byte.Parse(lookUpEdit1.EditValue.ToString());
            db.SaveChanges();
            MessageBox.Show("Ürün Güncellenmiştir", "Bilgi", MessageBoxButtons.OK, MessageBoxIcon.Warning);
        }

        private void btnlistele_Click(object sender, EventArgs e)
        {
            metot1();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            txtId.Text = "";
            txtmarka.Text = "";
            txtalis.Text = "";
            txtsatis.Text = "";
            txturun.Text = "";
            txtstok.Text = "";
            
        }
    }
}
