//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeDevexpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFATURABILGI
    {
        public int Id { get; set; }
        public Nullable<int> SıraNo { get; set; }
        public string Seri { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
        public string VergiDairesi { get; set; }
        public string Cari { get; set; }
        public string Personel { get; set; }
    }
}
