//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeDevexpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONEL
    {
        public short ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<byte> DEPARTMAN { get; set; }
        public string FOTOGRAF { get; set; }
        public string MAIL { get; set; }
        public string TELEFON { get; set; }
    
        public virtual TBLDEPARTMAN TBLDEPARTMAN { get; set; }
    }
}
